### ISSUE TITLE
Home Page: Background Images

### ISSUE THREAD

**Issue by shanedwilson** [nss-evening-cohort-8/bandz-mermaids-in-the-basement#1]
## Story
When the user sees the home page they should see scrolling background images.

## Acceptance Criteria
**When** the user is on the home page
**then** they see scrolling background images.

## Technical Notes
- index.html should be pulled down
- main.js should be pulled down
- main.css should be pulled down
- create object of images
- create function to iterate over images and change them over time
- print images to DOM

<img width="423" alt="screen shot 2018-09-10 at 8 11 38 pm" src="https://user-images.githubusercontent.com/40958758/45332376-d5395a80-b535-11e8-8b19-1a5056d97cc5.png">

**Comment by Shijax** [comment]
## Requested Feature

## Expected Function

## Developer Notes

## Acceptance Criteria

**Comment by Shijax** [comment]
### Possible Code:

```
<script type="text/javascript">
function changeBanner(){
    var img = new array

    img[0] = document.images[0].src
    img[1] = document.images[1].src
    img[2] = document.images[2].src

    var currentimg = img[0]

    if(currentimg == img[0]) {
        currentimg = img[1]
    }

    if(currentimg == img[1]) {
        currentimg = img[2]
    }
}

  setInterval('changeBanner()', 10000);
</script>
```
